# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: Upload binaries to release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
        goversion: [1.17]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_command: "go build -o btserver-${{ matrix.goos }}-${{ matrix.goarch }} peripheral/main.go"
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: btserver-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: btserver-${{ matrix.goos }}-${{ matrix.goarch }}
          tag: ${{ github.ref }}
